### PR TITLE
chore: update rc.1, use new router

### PR DESCRIPTION
**Pull request by NathanWalker**
Simple changes to allow usage of new router.
I will point to this commit explicitly for advanced seed in meantime as we are using the new router there.

### CODE REVIEW

**Comment by NathanWalker** [comment]
Hold on this at moment. Results in:

```
TypeError: Cannot read property 'distinctUntilChanged' of undefined
```

Meaning the `Router` does not get injected properly or `_subject` is not available from:

```
<Observable<string>>router['_subject']
```

**Comment by brandonroberts** [comment]
Yea, there are a couple more changes that need to be made. You can't use the ReflectiveInjector as a provider. The new router also doesn't emit the current URL after navigation, so it can't use distinctUntilChanged, and the observable is `_changes`. I apologize for not having tests setup 😦

**Comment by brandonroberts** [comment]
I merged your changes into a branch here and I'll update with that if its ok with you.

https://github.com/CodeSequence/ngrx-store-router/tree/chore/rc1-new-router

Thanks again for the PR!

**Comment by NathanWalker** [comment]
Awesome thanks @brandonroberts !

**Pull request closed without merging**
